development:
  adapter: postgresql
  database: jwitterp_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: jwitterp_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: jwitterp_production
  pool: 5
  timeout: 500
